stages:
  - stage: 
    displayName: Build
    pool: ubuntu-latest
    jobs:
      - job: 
        steps:
        - task: Gradle@3
          displayName: Compile
          inputs:
            gradleWrapperFile: 'gradlew'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            tasks: 'build'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            sonarQubeRunAnalysis: false
            checkStyleRunAnalysis: false
            spotBugsAnalysis: false
        - task: Gradle@3
          displayName: Create Jar
          inputs:
            gradleWrapperFile: 'gradlew'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            tasks: 'bootJar'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            sonarQubeRunAnalysis: false
            spotBugsAnalysis: false
       - task: Gradle@3
         displayName: Build Image
         inputs:
           gradleWrapperFile: 'gradlew'
           workingDirectory: '$(System.DefaultWorkingDirectory)'
           tasks: 'bootBuildImage'
           publishJUnitResults: false
           javaHomeOption: 'JDKVersion'
           jdkVersionOption: '1.17'
           sonarQubeRunAnalysis: false
           spotBugsAnalysis: false
       - bash: | 
           get_image_tag=$(docker images stanislavzhurich/pilot-user-service:* --format='{{.Tag}}' | head -1)
           echo "##vso[task.setvariable variable=IMAGE_TAG]$get_image_tag"
       - bash: |
           echo "$(IMAGE_TAG)"
       - task: Docker@2
         displayName: Login to Docker Hub
         inputs:
           containerRegistry: 'DockerHubConnection'
           command: 'login'
       - task: Docker@2
         displayName: Push Image
         inputs:
           containerRegistry: 'DockerHubConnection'
           repository: 'stanislavzhurich/pilot-user-service'
           command: 'push'
           tags: '$(IMAGE_TAG)'