resources:
  pipelines:
  - pipeline: DeployUserService # Name of the pipeline resource.
    source: "Build User Service" # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

steps:
- bash: echo "app-ci runs after security-lib-ci completes"