stages:
    - stage: test 
      jobs:
          - job: 
            steps:
            - task: CmdLine@2
              inputs:
                script: |
                  echo "Structure of work folder of this pipeline:"
                  tree $(System.DefaultWorkingDirectory)
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  $fileExists1 = Test-Path -Path "$(System.DefaultWorkingDirectory)/gradle"
                  Write-Output "##vso[task.setvariable variable=FileExists2]$fileExists1"
            - bash: |
                fileExists=$([ -d "/gradle" ])
                echo "##vso[task.setvariable variable=RUN_TERRAFORM]$fileExists"
              workingDirectory: $(System.DefaultWorkingDirectory)
            - task: CmdLine@2
              inputs:
                script: 'echo test $(FileExists2)'