stages:
    - stage: test 
      jobs:
          - job: 
            steps:
            - bash: |
                fileExists=$([ -d "/gradle" ])
                echo "##vso[task.setvariable variable=RUN_TERRAFORM]$fileExists"
              workingDirectory: $(System.DefaultWorkingDirectory)
            - task: CmdLine@2
              inputs:
                script: 'echo test $(RUN_TERRAFORM)'