server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
spring:
  cloud:
    azure:
      cosmos:
        enabled: true
        credential:
          client-id: ${service_sp_id}
          client-secret: ${service_sp_pswd}
        endpoint: https://develop-pilot-account.documents.azure.com:443/
        database: user-container
        profile: 
           tenant-id: ${service_sp_tenant_id}
      keyvault:
        secret:
          enabled: true
          property-sources:
            - name: develop-pilot-kv
              endpoint: https://develop-pilot-kv.vault.azure.net/
              credential:
                managed-identity-enabled: true
                client-id: 571cd73b-e5e9-4379-8470-48dc5da66ff2 #${service_sp_id}
                #client-secret: ${service_sp_pswd}
              profile: 
                tenant-id: ${service_sp_tenant_id}
            