
#spring:
 # profiles:
  #  active: local
server:
  port: 8080
logging:
  level:
    com.azure: DEBUG
management:
  endpoints:
    enabled-by-default: true
spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${aks_mi_client_id}
      keyvault:
        secret:
          enabled: true
          property-sources:
            - name: develop-pilot-kv
              endpoint: https://develop-pilot-kv.vault.azure.net/
            