# Default values for pilot-user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: stanislavzhurich/pilot-user-service
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: kubernetes.docker.internal
      paths:
        - path: /users
