# Default values for pilot-user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceAccountName: pilotserviceaccount

envValues:
  - name: SPRING_PROFILES_ACTIVE
    value: develop

image:
  repository: stanislavzhurich/pilot-user-service

service:
  type: ClusterIP
  port: 80
  targetPort: 8080


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - paths:
        - path: /users
        - path: /actuator/health/liveness
        - path: /actuator/health/readiness
        - path: /actuator
