# Starter pipeline
trigger:
- develop
resources:
  repositories:
    - repository: pilot-infrastructure
      endpoint: stanislavzhurich
      type: github
      name: stanislav-zhurich/pilot-infrastructure
      ref: refs/heads/develop
stages: 
  - template: /pipelines/templates/build-service-template.yml@pilot-infrastructure
    parameters:
      ServiceName: pilot-user-service

