# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
resources:
  repositories:
    - repository: pilot-infrastructure
      endpoint: stanislavzhurich
      type: github
      name: pilot-infra/pilot-infrastructure
      ref: refs/heads/develop
stages: 
  - template: /pipelines/templates/build-service-template.yml@pilot-infrastructure
    parameters:
      ServiceName: pilot-user-service

