# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
resources:
  pipelines:
  - pipeline: Build User Service # Name of the pipeline resource.
    source: Build User Service # The name of the pipeline referenced by this pipeline resource.
    trigger:
      branches:
        include:
          - develop
variables:
  - name: ServiceName
    value: pilot-user-service
  - name: DockerAccountName
    value: stanislavzhurich
stages: 
  - stage: Deploy
    displayName: Deploy
    pool: Azure Pipelines
    jobs:
      - job: 
        steps:
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'develop_aks_service_endpoint'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: './pilot-user-service'
            chartVersion: '$(IMAGE_TAG)'
            releaseName: 'pilot-user-service'
            valueFile: './pilot-user-service/values-develop.yaml'
            arguments: '--atomic'


