trigger: none
resources:
    pipelines:
    - pipeline: "Build User Service"
      source: Build User Service # The name of the pipeline referenced by this pipeline resource.
      trigger:
        branches:
          include:
            - develop
    repositories:
      - repository: pilot-infrastructure
        endpoint: stanislavzhurich
        type: github
        name: stanislav-zhurich/pilot-infrastructure
        ref: refs/heads/develop
stages: 
  - template: /pipelines/templates/deploy-service-template.yml@pilot-infrastructure
    parameters:
      ServiceName: pilot-user-service
      RunTerraform: True
      RunPostDeploymentTerraform: True
