# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest
steps:
- task: Gradle@3
  displayName: Compile
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: false
    spotBugsAnalysis: false
- task: Gradle@3
  displayName: Create Jar
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    tasks: 'bootJar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: Gradle@3
  displayName: Build Image
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    tasks: 'bootBuildImage'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- bash: | 
    docker_latest_image=$(docker --version)
    echo "##vso[task.setvariable variable=DOCKER_IMAGE]$docker_latest_image"
- bash: |
      echo "$(DOCKER_IMAGE)"
- task: Docker@2
  inputs:
    command: 'push'


