stages:
    - stage: test 
      
      jobs:
          - job: 
            steps:
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  $fileExists1 = Test-Path -Path "$(System.DefaultWorkingDirectory)/terraform1"
                  Write-Output "##vso[task.setvariable variable=FileExists2]$fileExists1"
            - task: CmdLine@2
              condition: eq(variables['FileExists2'], 'True')
              inputs:
                script: |
                  echo "Structure of work folder of this pipeline:"
                  tree $(System.DefaultWorkingDirectory)